config/routes.rb
Rails.application.routes.draw do
  resources :bookings
  resources :transactions
  resources :posts
  post "posts/book/" => "posts#book"
  resources :post_images
  root to: 'visitors#index'
  devise_for :users
  get "users/profile/" => "users#profile" , as: 'user_profile'
  resources :users
end

app/models/booking.rb
class Booking < ActiveRecord::Base
  belongs_to :user, :class_name => 'User'
  belongs_to :money, foreign_key: "transaction_id", :class_name => 'Transaction'
  belongs_to :post, :class_name => 'Post'
end

app/controllers/bookings_controller.rb
require 'will_paginate/array'

class BookingsController < ApplicationController
  before_action :set_booking, only: [:show, :edit, :update, :destroy]

  # GET /bookings
  # GET /bookings.json
  def index
    @bookings = Booking.all.paginate(:page => params[:page]) if stale?(Booking.all.paginate(:page => params[:page]))
  end

  # GET /bookings/1
  # GET /bookings/1.json
  def show
    fresh_when(@booking)
  end

  # GET /bookings/new
  def new
    fresh_when(@booking)
    @booking = Booking.new
  end

  # GET /bookings/1/edit
  def edit
    fresh_when(@booking)
  end

  # POST /bookings
  # POST /bookings.json
  def create
    @booking = Booking.new(booking_params)

    respond_to do |format|
      if @booking.save
        format.html { redirect_to @booking, notice: 'Booking was successfully created.' }
        format.json { render :show, status: :created, location: @booking }
      else
        format.html { render :new }
        format.json { render json: @booking.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bookings/1
  # PATCH/PUT /bookings/1.json
  def update
    fresh_when(@booking)
    respond_to do |format|
      if @booking.update(booking_params)
        format.html { redirect_to @booking, notice: 'Booking was successfully updated.' }
        format.json { render :show, status: :ok, location: @booking }
      else
        format.html { render :edit }
        format.json { render json: @booking.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bookings/1
  # DELETE /bookings/1.json
  def destroy
    post = Post.find(@booking.post_id)
    post.booking_id = nil
    post.save!
    @booking.destroy
    respond_to do |format|
      format.html { redirect_to :back, notice: 'Booking was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_booking
      @booking = Booking.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def booking_params
      params.require(:booking).permit(:user_id, :transaction_id, :post_id)
    end
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/views/bookings/_form.html.erb
<%= form_for(@booking) do |f| %>
  <% if @booking.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@booking.errors.count, "error") %> prohibited this booking from being saved:</h2>

      <ul>
      <% @booking.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.text_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :transaction_id %><br>
    <%= f.text_field :transaction_id %>
  </div>
  <div class="field">
    <%= f.label :post_id %><br>
    <%= f.text_field :post_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/bookings/edit.html.erb
<h1>Editing Booking</h1>

<%= render 'form' %>

<%= link_to 'Show', @booking %> |
<%= link_to 'Back', bookings_path %>

app/views/bookings/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Bookings</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Transaction</th>
      <th>Post</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
  <% @bookings.each do |booking| %>
      <tr>
        <td><%= booking.user.id %></td>
        <td><%= booking.money.id %></td>
        <td><%= booking.post.id %></td>
        <td><%= link_to 'Show', booking %></td>
        <td><%= link_to 'Edit', edit_booking_path(booking) %></td>
        <td><%= link_to 'Destroy', booking, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
  <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Booking', new_booking_path %>
<%= will_paginate @bookings %>

app/views/bookings/new.html.erb
<h1>New Booking</h1>

<%= render 'form' %>

<%= link_to 'Back', bookings_path %>

app/views/bookings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @booking.user %>
</p>

<p>
  <strong>Transaction:</strong>
  <%= @booking.money %>
</p>

<p>
  <strong>Post:</strong>
  <%= @booking.post %>
</p>

<%= link_to 'Edit', edit_booking_path(@booking) %> |
<%= link_to 'Back', bookings_path %>