config/routes.rb
Rails.application.routes.draw do
  resources :bookings
  resources :transactions
  resources :posts
  post "posts/book/" => "posts#book"
  resources :post_images
  root to: 'visitors#index'
  devise_for :users
  get "users/profile/" => "users#profile" , as: 'user_profile'
  resources :users
end

app/models/post_image.rb
class PostImage < ActiveRecord::Base
  belongs_to :post
  has_attached_file :image
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/
end

app/controllers/post_images_controller.rb
require 'will_paginate/array'

class PostImagesController < ApplicationController
  before_action :set_post_image, only: [:show, :edit, :update, :destroy]

  # GET /post_images
  # GET /post_images.json
  def index
    @post_images = PostImage.all.paginate(:page => params[:page]) if stale?(PostImage.all.paginate(:page => params[:page]))
  end

  # GET /post_images/1
  # GET /post_images/1.json
  def show
    fresh_when(@post_image)
  end

  def book
  end

  # GET /post_images/new
  def new
    @post_image = PostImage.new(post_id: params[:post_id]) if stale?(PostImages.all)
    all_posts = Post.all.paginate(:page => params[:page]) if stale?(Post.all.paginate(:page => params[:page]))
    @options = all_posts.collect do |s|
      [s.name, s.id]
    end
  end

  # GET /post_images/1/edit
  def edit
    @options = Post.find(:all,
                            :order => "name").
    collect do |s|
      [s.name, s.id]
    end
  end

  # POST /post_images
  # POST /post_images.json
  def create
    @post_image = PostImage.new(post_image_params)

    respond_to do |format|
      if @post_image.save
        format.html { redirect_to @post_image, notice: 'Post image was successfully created.' }
        format.json { render :show, status: :created, location: @post_image }
      else
        format.html { render :new }
        format.json { render json: @post_image.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /post_images/1
  # PATCH/PUT /post_images/1.json
  def update
    fresh_when(@post_image)
    respond_to do |format|
      if @post_image.update(post_image_params)
        format.html { redirect_to @post_image, notice: 'Post image was successfully updated.' }
        format.json { render :show, status: :ok, location: @post_image }
      else
        format.html { render :edit }
        format.json { render json: @post_image.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /post_images/1
  # DELETE /post_images/1.json
  def destroy
    @post_image.destroy
    respond_to do |format|
      format.html { redirect_to post_images_url, notice: 'Post image was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post_image
      @post_image = PostImage.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_image_params
      params.require(:post_image).permit(:image_url, :post_id)
    end
end

app/helpers/post_images_helper.rb
module PostImagesHelper
  def cache_key_for_post_image_row(post_image)
    "post_image-#{post_image.post.name}-#{post_image.image_url}"
  end
end

app/views/post_images/_form.html.erb
<%= form_for(@post_image, url: post_images_path, html: {multipart: true}) do |f| %>
  <% if @post_image.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post_image.errors.count, "error") %> prohibited this post_image from being saved:</h2>

      <ul>
      <% @post_image.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.file_field :image %><br>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/post_images/edit.html.erb
<h1>Editing Post Image</h1>

<%= render 'form' %>

<%= link_to 'Show', @post_image %> |
<%= link_to 'Back', post_images_path %>

app/views/post_images/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Post Images</h1>

<table>
  <thead>
    <tr>
      <th>Image url</th>
      <th>Post</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @post_images.each do |post_image| %>
      <% cache(cache_key_for_post_image_row(post_image)) do %>
          <tr>
            <td><%= post_image.image_url %></td>
            <td><%= post_image.post.name %></td>
            <td><%= link_to 'Show', post_image %></td>
            <td><%= link_to 'Edit', edit_post_image_path(post_image) %></td>
            <td><%= link_to 'Destroy', post_image, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
      <% end %>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Post image', new_post_image_path %>
<%= will_paginate @post_images %>

app/views/post_images/new.html.erb
<h1>New Post Image</h1>

<%= render 'form' %>

<%= link_to 'Back', post_images_path %>

app/views/post_images/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Image url:</strong>
  <%= @post_image.image_url %>
</p>

<p>
  <strong>Post:</strong>
  <%= @post_image.post_id %>
</p>

<%= link_to 'Edit', edit_post_image_path(@post_image) %> |
<%= link_to 'Back', post_images_path %>